### ISSUE TITLE
Games not working [Solution]

### ISSUE THREAD

**Issue by ghost** [entyX/jcteam#1]
The reason the games are not working is because you only put the local path of the files right here ""file:///home/chronos/u-ebbf0c765d56da71137ccbac17fe96ffca9f7252/MyFiles/coding%20projects/JC%20Website%20(temporary)/games/javascript-breakout.html"

The fix is to upload the files. Lets say for example we wanted to add the javascript-breakout game you would upload it to github and put the file path from github.

**Comment by entyX** [comment]
yeah im fixing it
